JS-961: Added The Course Project Setup
ct-aa/dotTheory---TypeScript pull request #1
Opened 2023-10-04 03:30 UTC by ct-aa

# Related Tickets
[JS-961](https://codeandtheory.atlassian.net/browse/JS-961)

# Description
- Added the Course Project Setup.

# Validation
- Open the terminal.
- Run `npm run start`.
- Inspect the web page that will be open.
- The console log test should appear.
<img width="1755" alt="Screen Shot 2023-10-04 at 11 30 00 AM" src="https://github.com/ct-aa/dotTheory---TypeScript/assets/93116252/27a1fc25-164c-4e8c-a3a0-e427c97abec4">

# Risks
N/A

2024-01-10 15:07 UTC, lycoangelo commented
Hi, @ct-aa, please remove the `node_modules` directory.

2024-01-10 15:07 UTC, lycoangelo requested changes
Hi, @ct-aa, please remove the `node_modules` directory.

2024-01-11 01:23 UTC, ct-aa commented
> Hi, @ct-aa, please remove the `node_modules` directory.

Thanks, @lycoangelo, This is updated now.

2024-01-23 05:42 UTC, lycoangelo approved these changes

2024-01-23 05:42 UTC, merged